[package]
name = "hivefriends"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
anyhow = "1.0.57"
axum = "0.5.4"
tokio = { version = "1.18.2", features = ["rt", "macros", "rt-multi-thread"] }
tracing = "0.1.34"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
