[package]
name = "hivefriends"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
anyhow = "1.0.57"
thiserror = "1.0.31"
axum = { version = "0.5.4", features = ["multipart", "headers"] }
tokio = { version = "1.18.2", features = ["fs", "rt", "macros", "rt-multi-thread"] }
tracing = "0.1.34"
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
rusqlite = { version = "0.27", features = ["bundled"] }
rusqlite_migration = "1.0"
deadpool-sqlite = "0.4"
lazy_static = "1.4"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
tracing-log = "0.1.3"
tracing-bunyan-formatter = "0.3.2"
rand = "0.8.5"
image = { version = "0.24", features = ["jpeg", "png"] }
blob-uuid = "0.5"
headers = "0.3.7"
argh = "0.1.7"
argon2 = { version = "0.4.0", features = ["std"] }
rpassword = "6.0.1"
